name: Build Binaries
on:
  workflow_dispatch:

jobs:
  build-darwin-x64:
    # this is currently macos-11, Big Sur
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: | 
          brew install make libelf freeglut patchelf 
          brew tap osx-cross/avr
          brew install avr-gcc@8 avr-binutils
          export PATH="/usr/local/opt/avr-gcc@5/bin:$PATH"
      - name: CI-Build
        run: |
          ln -s /usr/local/Cellar/avr-gcc@5/5.5.0/avr/include/avr simavr/cores/avr
          avr-gcc --version || true
          clang --version
          export CFLAGS="-DGL_SILENCE_DEPRECATION"
          make -j4 build-simavr V=1 RELEASE=1
          mkdir simavr_installed
          make -k -j4 install RELEASE=1 DESTDIR=$(pwd)/simavr_installed/ || true
          file simavr_installed/bin/*
          otool -L simavr_installed/bin/*
          simavr_installed/bin/simavr --list-cores || true
          cp -r examples simavr_installed
      - name: Test
        run: |
          cd tests
          export PATH="/usr/local/opt/avr-gcc@8/bin:/usr/local/opt/avr-binutils/bin:$PATH"
          make run_tests
      - uses: actions/upload-artifact@v3
        with:
          name: Simavr for Mac OS on 64-bit Intel
          path: simavr_installed

