name: Build Binaries
on:
  workflow_dispatch:

jobs:
  build-win64:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make mingw-w64-x86_64-toolchain mingw-w64-x86_64-libelf mingw-w64-x86_64-avr-toolchain mingw-w64-x86_64-freeglut
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ln -s /mingw64/avr/include/avr/ simavr/cores/avr
          make build-simavr V=1
          mkdir simavr_installed
          make -k install DESTDIR=$(pwd)/simavr_installed/ || true
          mv simavr_installed/bin/simavr simavr_installed/bin/simavr.exe
          file simavr_installed/bin/*
          cp -r examples simavr_installed
      - uses: actions/upload-artifact@v3
        with:
          name: Simavr for 64-bit Windows
          path: simavr_installed
  build-lin64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install -y build-essential git make gcc-avr avr-libc libelf-dev freeglut3-dev patchelf
      - name: CI-Build
        run: |
          ln -s /usr/lib/avr/include/avr/ simavr/cores/avr
          make build-simavr V=1 RELEASE=1
          mkdir simavr_installed
          make  install RELEASE=1 DESTDIR=$(pwd)/simavr_installed/
          file simavr_installed/bin/*
          patchelf --remove-needed ./libsimavr.so.1 simavr_installed/bin/simavr || true
          patchelf --add-needed libsimavr.so.1 simavr_installed/bin/simavr
          patchelf --set-rpath '$ORIGIN/../lib/' simavr_installed/bin/simavr
          ldd simavr_installed/bin/*
          simavr_installed/bin/simavr --list-cores || true
          cp -r examples simavr_installed
      - uses: actions/upload-artifact@v3
        with:
          name: Simavr for 64-bit Linux
          path: simavr_installed
  build-darwin-x64:
    # this is currently macos-11, Big Sur
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: | 
          brew install make libelf freeglut patchelf 
          brew tap osx-cross/avr
          brew install avr-gcc@5 avr-binutils
          export PATH="/usr/local/opt/avr-gcc@5/bin:$PATH"
      - name: CI-Build
        run: |
          ln -s /usr/local/Cellar/avr-gcc@5/5.5.0/avr/include/avr simavr/cores/avr
          avr-gcc --version || true
          clang --version
          export CFLAGS="-DGL_SILENCE_DEPRECATION"
          make -j4 build-simavr V=1 RELEASE=1
          mkdir simavr_installed
          make -k -j4 install RELEASE=1 DESTDIR=$(pwd)/simavr_installed/ || true
          file simavr_installed/bin/*
          otool -L simavr_installed/bin/*
          simavr_installed/bin/simavr --list-cores || true
	  cp -r examples simavr_installed
      - uses: actions/upload-artifact@v3
        with:
          name: Simavr for Mac OS on 64-bit Intel
          path: simavr_installed

